source {D:/Xilinx/data/projnav/scripts/VsimStopServer.tcl}
-- Auto Generated by Project Navigator to simulate
-- HDL Bencher Annotated Test Bench
--
vlib work
onbreak {resume}
onerror {quit -code 99 -force}
onElabError {resume}
vcom -explicit  -93 "game.vhd"
vcom -explicit  -93 "GAME.ant"
vsim -t 1ps   -lib work GAME
run -all
quit -force
